# Generated by Django 4.2.3 on 2023-07-16 18:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco_diferente', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=3)),
                ('rua_medido', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_medido', models.CharField(blank=True, max_length=100, null=True)),
                ('frente', models.FloatField()),
                ('fundo', models.FloatField()),
                ('lado_direito', models.FloatField(null=True)),
                ('lado_esquerdo', models.FloatField(null=True)),
                ('area', models.FloatField()),
                ('perimetro', models.FloatField()),
                ('frente_com', models.CharField(blank=True, max_length=100, null=True)),
                ('esquerda_com', models.CharField(blank=True, max_length=100, null=True)),
                ('direita_com', models.CharField(blank=True, max_length=100, null=True)),
                ('fundo_com', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('documento', models.CharField(max_length=255, null=True)),
                ('primeiro_dono', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('num_documento', models.IntegerField()),
                ('expedir_titulo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=3, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_fiscalizacao', models.DateField()),
                ('fiscal_1', models.CharField(blank=True, max_length=100, null=True)),
                ('fiscal_2', models.CharField(blank=True, max_length=100, null=True)),
                ('agente_medicao', models.CharField(max_length=100)),
                ('foto_termo_medicao', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
